### ISSUE TITLE
UI Preparation For The TG Gated Groups

### ISSUE THREAD

**Issue by charmful0x** [decentldotland/ark-ui#21]
## About
Integrate the guilds creation feature on [ark.decent.land](https://ark.decent.land).

## 1- Missing component in the current UI
In the Ark UI alpha release, users can only link the address's identity. To enable the Ark TG Bot feature, the user should also be able to provide his TG username inside his Ark identity object.

#### A- For users with identity already created:
The user passes his Telegram username (with the `@`) in the UI TG field (form with the addresses?)
```json
{"function": "linkIdentity", "telegram_enc": "U2FsdGVkX18FU42ezv3trajaYMcQdE/qnQDeAK6nxu8="}
```
#### B- For new users wishing to link their addresses & TG username

```json
{
  "function": "linkIdentity",
  "address": "0x197f818c1313dc58b32d88078ecdfb40ea822614",
  "verificationReq": "0xa9bf5f00cb91e9dcf5e5c441b9b7fa8fa0078f3240a568d5d960f5a5e6e2ac56",
  "network": "BSC-MAINNET",
  "telegram_enc": "U2FsdGVkX18FU42ezv3trajaYMcQdE/qnQDeAK6nxu8="
}

```
## 2- Task: guild object creation
The task is to provide a component in the UI where **only** Ark users (users who have identity [verified & evaluated](https://thawing-lowlands-08726.herokuapp.com/ark/oracle/state) on Ark Protocol) can create a **guild object**.

### What's a guild object?
A guild object is an object in the guild's registry state (SmartWeave Contract) that holds the guild's metadata. The TG group admin has to create a guild object first, to be able to link it with their private TG group after the successful guild object creation.

### How to create a guild object?
After logging in using Arconnect, the user can create his guild after filling the creation form with the SWC function interaction's input. [Check it on github here](https://github.com/decentldotland/ark-network-bot#guild-creation).

***N.B: the resulting TXID of the guild's creation interaction is the unique `guild_id`***

### Additional UX
For the users who have created guilds, display their created guild objects (either linked or not) in the `ark.decent.land/account` page section. i will provide an HTTP GET endpoint for it later on.

### Prerequisites:
- Guild creators must verify their telegram username with their Ark identity before linking the guild on Telegram.
- Any user willing to join a guild should also verify his telegram username with his Ark identity.
- verifying the telegram username happens by DMing the Ark bot `/verify_username <caller_ark_identity_id>` [check the code here](https://github.com/decentldotland/ark-network-bot/blob/main/src/app.js#L172) 

### A- linking a TG private group to a guild object
- Ark's TG bot must have the admin's privileges.
- only the group admin/creator can invoke the command.
- The group is linked to the guild via the `guild_id` (in the group).

![image](https://user-images.githubusercontent.com/77340894/181600261-8549b19d-3598-4ebb-ac62-b9c33d9a07e5.png)

### B- Users joining a token-gated TG group 
- The user must have a valid Ark identity (addresses + telegram_username evaluated and verified).
- The chain used by the user to link his addresses on [ark.decent.land](https://ark.decent.land) does not affect joining guilds of different chains.
- The user can request an invitation link only for one time. (alpha release limitation).
- The invitation link is valid for 1 user entry only.
- The user join a guild by invoking the joining command with the `guild_id` as argument (DM the bot).

![image](https://user-images.githubusercontent.com/77340894/181601062-3bfd6070-7ab6-4734-b19e-9e5c6ff3d7ef.png)

## Helpful links
- [Ark Telegram bot repo](https://github.com/decentldotland/ark-network-bot)
-  guilds registry contract: [sWR6h_DrFHBS2P2-l1zYFo0R7ufJy32YINM1UVP7f5w](https://viewblock.io/arweave/address/sWR6h_DrFHBS2P2-l1zYFo0R7ufJy32YINM1UVP7f5w?tab=state)
## Author
@charmful0x

**Comment by maxknivets** [comment]
❌ Temporarily scrapped for now
