### ISSUE TITLE
Near Network Integration

### ISSUE THREAD

**Issue by charmful0x** [decentldotland/ark-ui#23]
## About 
Integration of Near network in the UI. Mainnet Near network is considered an `Exotic Network` (non-EVM) in the Ark Network.

## Required Changes
The function of linking an exotic address to your identity in the Ark Network Oracle [v0.0.9](https://github.com/decentldotland/ark-network/blob/main/ark-contracts/arweave/exotic-identity.js) is different than the function for EVM addresses linkage ([check it in the repo's code](https://github.com/decentldotland/ark-ui/blob/main/src/pages/index.tsx#L96)).

So for any user trying to link his Arweave address with a Near address, the SWC interaction should be as follow:

- Ark Oracle v0.0.9: [5H5Hj81G5j5P2raDhe5VFU-zkf08KDc588GJ8dtlHTw](https://viewblock.io/arweave/address/5H5Hj81G5j5P2raDhe5VFU-zkf08KDc588GJ8dtlHTw)
```json
{
  "function": "linkExoticIdentity",
  "address": "abc.near",
  "verificationReq": "...",
  "network": "NEAR-MAINNET" // Near mainnet network identifier
}
```
notice that the only diff is the function's name `linkEvmIdentity` -> `linkExoticIdentity`

**Comment by maxknivets** [comment]
✅ Integrated a while ago
